[Icon Theme]
Name=Kaklat
Comment=Kakalall asdsadasdsad
Inherits=breeze,hicolor

Directories=scalable/apps,scalable/status,scalable/places,22x22/places,16x16/places

[scalable/apps]
Size=32
Context=Applications
Type=Scalable

[scalable/status]
Size=48
Context=Status
Type=Scalable

[scalable/places]
Size=32
Context=Places
Type=Scalable

[22x22/places]
Size=22
Context=Places
Type=Fixed

[16x16/places]
Size=16
Context=Places
Type=Fixed
